name: space_shooter
description: "A new Flutter project."
publish_to: 'none'
version: 0.3.15

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  flame_audio: ^2.1.0
  shared_preferences: ^2.2.2
  http: ^1.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/changelog.json
    - .env
